- name: Install Nginx on Linux
  hosts: all
  become: true
  tasks:
    - name: Install Nginx on Ubuntu
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx on Amazon Linux
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure the correct document root exists on Ubuntu
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      when: ansible_os_family == "Debian"

    - name: Ensure the correct document root exists on Amazon Linux
      file:
        path: /usr/share/nginx/html
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'
      when: ansible_os_family == "RedHat"

    - name: Copy index.html to the correct directory on Ubuntu
      template:
        src: index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      when: ansible_os_family == "Debian"

    - name: Copy index.html to the correct directory on Amazon Linux
      template:
        src: index.html
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'
      when: ansible_os_family == "RedHat"

    - name: Start Nginx and enable it on startup
      service:
        name: nginx
        state: started
        enabled: true