- name: Uninstall Docker on Linux
  hosts: all
  become: true
  tasks:
    - name: Stop Docker service
      service:
        name: docker
        state: stopped
        enabled: false
      ignore_errors: yes

    - name: Remove Docker package on Ubuntu
      apt:
        name: docker-ce
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Remove Docker dependencies on Ubuntu
      apt:
        name:
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Remove Docker repository on Ubuntu
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove Docker package on Amazon Linux
      yum:
        name: docker
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove Docker directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/docker
        - /etc/docker
        - /var/run/docker.sock
      ignore_errors: yes
