- name: Install Nginx on Amazon Linux
  hosts: group_B2111933\ Amazon\ Linux
  become: yes
  gather_facts: yes
  tasks:
    - name: Install Nginx (RHEL-based)
      yum:
        name: nginx
        state: present
      when: ec2_tag_Name is defined and ec2_tag_Name == "B2111933 Amazon Linux"

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: true
      when: ec2_tag_Name is defined and ec2_tag_Name == "B2111933 Amazon Linux"

- name: Install Nginx on Ubuntu
  hosts: group_B2111933\ Ubuntu
  become: yes
  gather_facts: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ec2_tag_Name is defined and ec2_tag_Name == "B2111933 Ubuntu"

    - name: Install Nginx (Debian-based)
      apt:
        name: nginx
        state: present
      when: ec2_tag_Name is defined and ec2_tag_Name == "B2111933 Ubuntu"

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: true
      when: ec2_tag_Name is defined and ec2_tag_Name == "B2111933 Ubuntu"

# - name: Install Nginx on Windows
#   hosts: group_B2111933\ Windows
#   gather_facts: no
#   vars:
#     ansible_user: "adminr"  
#     ansible_password: "admin"
#     ansible_connection: winrm
#     ansible_winrm_server_cert_validation: ignore
#   tasks:
#     - name: Ensure Chocolatey is installed
#       win_chocolatey:
#         name: chocolatey
#         state: present
#       when: ec2_tag_Name is defined and ec2_tag_Name == "B2111933 Windows"

#     - name: Install Nginx via Chocolatey
#       win_chocolatey:
#         name: nginx
#         state: present
#       when: ec2_tag_Name is defined and ec2_tag_Name == "B2111933 Windows"

#     - name: Start Nginx service (if available)
#       win_service:
#         name: nginx
#         state: started
#         start_mode: auto
#       when: ec2_tag_Name is defined and ec2_tag_Name == "B2111933 Windows"
