- name: Remove Nginx on Linux
  hosts: all
  become: true
  tasks:
    - name: Stop and disable Nginx service
      service:
        name: nginx
        state: stopped
        enabled: false

    - name: Remove Nginx on Ubuntu
      apt:
        name: nginx
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Remove Nginx on Amazon Linux
      yum:
        name: nginx
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove index.html from Ubuntu document root
      file:
        path: /var/www/html/index.html
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove index.html from Amazon Linux document root
      file:
        path: /usr/share/nginx/html/index.html
        state: absent
      when: ansible_os_family == "RedHat"
