name: Manual Apply # To prevent using a stale plan file, please run the Integrate workflow again.

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6

      - name: Download Planfile Artifact
        uses: dawidd6/action-download-artifact@v7
        with:
          workflow: integrate.yml
          name: terraform-planfile

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -input=false planfile

      - name: Extract Inventory from Terraform
        run: |
          terraform output -raw ansible_inventory > ansible/inventory/aws_ec2.yaml

      - name: Upload Inventory Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-inventory
          path: ansible/inventory/aws_ec2.yaml

  config:
    runs-on: ubuntu-latest
    needs: apply # Run after terraform apply
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Inventory Artifact
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory
          path: ansible/inventory/

      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory/aws_ec2.yaml ansible/playbooks/nginx.yml
